<?php
/**
* what gets replaced with what in what conjugation
*
* first is the base that gets removed
* second is I and you
* third is he/she/we/you
* fourth is they
*/

$words = array(
  // -- aa
  "aakkostaa" =>  array("aa", 
                        "a", "taa", "a"),
  "aallottaa" =>  array("taa",
                        "a", "taa", "ta"),
  "aavistaa" =>   array("aa",
                        "a", "aa", "a"),
  "ahtaa" =>      array("taa",
                        "da", "taa", "taa"),
  "alustaa" =>    array("taa",
                        "ta", "taa", "ta"),
  "ammentaa" =>   array("taa",
                        "na", "taa", "ta"),
  "soutaa" =>     array("taa",
                        "da", "taa", "ta"),
  "askeltaa" =>     array("taa",
                        "la", "taa", "ta"),
  "avartaa" =>     array("taa",
                        "ra", "taa", "ta"),
  // -- ea
  "imeä" =>  array("ä",
                        "", "e", ""),
  // -- da
  "aateloida" =>  array("da",
                        "", "", ""),
  "tehdä" =>  array("hdä",
                        "e", "kee", "ke"),
  "chatata" =>    array("ata",
                        "aa", "aa", "aa"),
  "delata" =>     array("ata",
                        "aa", "aa", "aa"),
  "buukata" =>    array("ata",
                        "kaa", "kaa", "kaa"),
  // -- ia
  "ahnehtia" =>   array("tia",
                        "di", "tii", "ti"),
  "ahmia" =>      array("a",
                        "", "i", ""),
  "empiä" =>      array("piä",
                        "mi", "pii", "pi"),
  "etsiä" =>      array("iä",
                        "i", "ii", "i"),
  // -- la
  "aavistella" => array("la",
                        "e", "ee", "e"),
  "anella" =>     array("la",
                        "e", "ee", "e"),
  "annella" =>    array("nella",
                        "na", "taa", "ta"),
  // -- ta
  "erota" =>      array("ota",
                        "oa", "oa", "oa"),
  "lotota" =>     array("ota",
                        "toa", "toaa", "toa"),
  "aallota" =>    array("lota", "toa", "lottaa", "toa"),
  "aplodeerata" => array("ata",
                        "aa", "aa", "aa"),
  "ahdata" =>     array("data",
                        "taa", "taa", "taa"),
  "haista" =>     array("ta",
                        "e", "taa", "e"),
  "syöstä" =>     array("stä",
                        "kse", "ksee", "kse"),
  "poista" =>     array("a",
                        "a", "aa", "a"),
  "bluffata" =>   array("ta",
                        "a", "a", "a"),
  "blondata" =>   array("ta",
                        "a", "a", "a"),
  "edetä" =>      array("detä",
                        "tene", "tenee", "tene"),
  "haaleta" =>   array("ta",
                        "ne", "nee", "ne"),
  "harkita" =>   array("ta",
                        "tse", "tsee", "tse"),
  "hillota" =>   array("ta",
                        "a", "aa", "a"),
  // -- ua
  "aavikoitua" => array("tua",
                        "du", "tuu", "tu"),
  "ahdistua" =>   array("a",
                        "", "u", ""),
  "ampua" =>      array("pua",
                        "mu", "muu", "pu"),
  "alentua" =>    array("tua",
                        "nu", "tuu", "tu"),
  "alittua" =>    array("tua",
                        "a", "taa", "tu"),
  "avartua" =>    array("tua",
                        "ru", "tuu", "tu"),
  // -- ee
  "erkanee" =>    array("ee",
                        "e", "e", "e"),
);
