<?php

/**
* what gets replaced with what. Third one is plural
* fex. "huopa" => array("pa", "va", "pie"),
* genitive => huo va n
* plural => huo va t
* plural genitive => huo pie n
* words are reverse sorted with some reorganizing as the best match is picked first 
* fex. we have 2 akkaus words. First the more common version and then the exception
*  "pakkaus" => array("s", "kse", "ksie"), // same as hakkaus, sakkaus, kakkaus, lakkaus
*  "rakkaus" => array("s", "de", "ksie"), // the exception
* 
*/
$words = array(
  // -- aa
  "nugaa" => array("a", "", "ide"),
  "maa" => array("a", "a", "ide"),
  "vapaa" => array("a", "a", "ide"),
  // -- ea
  "korkea" => array("a", "a", "ide"),
  // -- ia
  "topografia" => array("a", "a", "oide"),
  "filosofia" => array("a", "a", "oide"),
  "analogia" => array("a", "a", "oide"),
  // -- ja
  "apaja" => array("a", "a", "oide"),
  "kantaja" => array("a", "a", "ie"),
  "kulkija" => array("a", "a", "oide"),
  "oja" => array("a", "a", "ie"),
  // -- ka
  "raaka" => array("ka", "'a", "koje"),
  "haka" => array("ka", "a", "koje"),
  "nahka" => array("ka", "a", "koje"),
  "karahka" => array("a", "a", "oje"),
  "aika" => array("ika", "ja", "ikoje"),
  "liika" => array("ka", "a", "koje"),
  "poika" => array("ika", "ja", "ikie"),
  "sika" => array("ka", "a", "koje"),
  "solakka" => array("ka", "a", "oide"),
  "hoikka" => array("ka", "a", "kie"),
  "hanka" => array("ka", "ga", "koje"),
  "honka" => array("ka", "ga", "kie"),
  "joka" => array("ka", "nka", "ide"),
  "ruoka" => array("oka", "oa", "okie"),
  // -- la
  "kala" => array("a", "a", "oje"),
  "jumala" => array("a", "a", "ie"),
  "matala" => array("a", "a", "ie"),
  "apila" => array("a", "a", "oide"),
  "loitolla" => array("la", "lamma", "lammaide"),
  // -- ma
  "asema" => array("a", "a", "ie"),
  "voima" => array("ma", "ma", "mie"),
  // -- na
  "sivumpana" => array("pana", "ma", "mie"),
  "markkina" => array("a", "a", "oide"),
  "peruna" => array("a", "a", "oide"),
  "pasuuna" => array("a", "a", "oide"),
  // -- oa
  "ainoa" => array("a", "o", "ide"),
  // -- pa
  "napa" => array("pa", "va", "poje"),
  "halpa" => array("pa", "va", "poje"),
  "kampa" => array("pa", "ma", "poje"),
  "kompa" => array("pa", "ma", "pie"),
  "huopa" => array("pa", "va", "pie"),
  "kappa" => array("pa", "a", "poje"),
  "ulappa" => array("pa", "a", "oide"),
  "tolppa" => array("pa", "a", "pie"),
  "lupa" => array("pa", "va", "pie"),
  // -- ra
  "makkara" => array("a", "a", "oide"),
  "koira" => array("a", "a", "ie"),
  // -- sa
  "kisa" => array("sa", "sa", "soje"),
  // -- ta
  "pata" => array("ta", "da", "toje"),
  "juhta" => array("ta", "da", "tie"),
  "riita" => array("ta", "da", "toje"),
  "valta" => array("ta", "la", "toje"),
  "kulta" => array("ta", "la", "tie"),
  "vihanta" => array("ta", "na", "toje"),
  "kanta" => array("ta", "na", "toje"),
  "veranta" => array("ta", "na", "tie"),
  "suunta" => array("ta", "na", "tie"),
  "kota" => array("ta", "da", "tie"),
  "parta" => array("ta", "ra", "toje"),
  "turta" => array("ta", "ra", "tie"),
  "alusta" => array("a", "a", "oje"),
  "aitta" => array("ta", "a", "toje"),
  "savotta" => array("ta", "a", "oide"),
  "pouta" => array("ta", "da", "tie"),
  // -- ua
  "herttua" => array("ua", "ua", "uoide"),
  // -- ab
  "kebab" => array("b", "bi", "bie"),
  // -- rc
  "farc" => array("c", "ci", "cie"),
  // -- nd
  "band" => array("d", "di", "die"),
  // -- ae
  "tae" => array("e", "kee", "keide"),
  // -- be
  "bebe" => array("e", "e", "eide"),
  // -- de
  "sade" => array("de", "tee", "teide"),
  // -- ee
  "tee" => array("e", "e", "ide"),
  // -- ge
  "college" => array("e", "e", "eide"),
  // -- he
  "pahe" => array("e", "ee", "eide"),
  // -- ie
  "aie" => array("e", "kee", "keide"),
  "tie" => array("ie", "ie", "eide"),
  // -- je
  "lahje" => array("je", "kee", "keide"),
  "ohje" => array("e", "ee", "eide"),
  "purje" => array("e", "ee", "eide"),
  // -- ke
  "eläke" => array("e", "kee", "keide"),
  "tarvike" => array("e", "kee", "keide"),
  "suihke" => array("e", "ee", "eide"),
  "nukke" => array("ke", "e", "keje"),
  // -- le
  "suikale" => array("e", "ee", "eide"),
  "nalle" => array("e", "e", "eje"),
  "helle" => array("le", "tee", "teide"),
  "joule" => array("e", "e", "eide"),
  // -- me
  "hame" => array("e", "ee", "eide"),
  "amme" => array("e", "ee", "eide"),
  "lumme" => array("me", "pee", "peide"),
  "käärme" => array("e", "ee", "eide"),
  "me" => array("e", "eidä", "eitte"),
  // -- ne
  "aine" => array("e", "ee", "eide"),
  "akne" => array("e", "e", "eje"),
  "enne" => array("ne", "tee", "teide"),
  // -- oe
  "koe" => array("e", "kee", "keide"),
  // -- pe
  "lape" => array("e", "pee", "peide"),
  // -- re
  "utare" => array("e", "ee", "eide"),
  "vire" => array("e", "ee", "eide"),
  "kierre" => array("re", "tee", "teide"),
  // -- se
  "ase" => array("e", "ee", "eide"),
  "rose" => array("e", "e", "eide"),
  // -- te
  "vaate" => array("e", "tee", "teide"),
  "liete" => array("te", "ttee", "tteide"),
  "osoite" => array("ite", "ittee", "itteide"),
  "polte" => array("te", "ttee", "tteide"),
  "tiedote" => array("te", "ttee", "tteide"),
  "raaste" => array("e", "ee", "eide"),
  "atte" => array("te", "e", "teide"),
  "palaute" => array("te", "ttee", "tteide"),
  "näyte" => array("te", "ttee", "tteide"),
  // -- ue
  "alue" => array("e", "ee", "eide"),
  // -- ve
  "taive" => array("ve", "pee", "peide"),
  "viive" => array("ve", "pee", "veide"),
  "tarve" => array("ve", "pee", "peide"),
  "terve" => array("e", "ee", "eide"),
  "katve" => array("ve", "vee", "veide"),
  // -- ye
  "yhtye" => array("e", "ee", "eide"),
  // -- lf
  "golf" => array("f", "fi", "fie"),
  // -- ng
  "doping" => array("g", "gi", "gie"),
  // -- ah
  "leah" => array("h", "hi", "hie"),
  // -- di
  "balladi" => array("i", "i", "eide"),
  "marinadi" => array("adi", "adi", "adie"),
  "pyramidi" => array("idi", "idi", "idie"),
  // -- fi
  "biografi" => array("afi", "afi", "afie"),
  // -- hi
  "kaihi" => array("i", "e", "ie"), 
  "tilhi" => array("i", "e", "ie"), 
  "hanhi" => array("i", "e", "ie"), 
  "karhi" => array("i", "e", "ie"), 
  "kärhi" => array("i", "e", "ie"), 
  "närhi" => array("i", "e", "ie"), 
  // -- ii
  "pii" => array("i", "i", "ide"),
  // -- ki
  "laki" => array("ki", "e", "kie"), 
  "reki" => array("ki", "e", "kie"),
  "hiki" => array("ki", "e", "kie"),
  "piki" => array("ki", "e", "kie"), 
  "kajakki" => array("ki", "i", "kie"),
  "takki" => array("ki", "i", "kie"),
  "kaikki" => array("ki", "e", "kie"), 
  "leikki" => array("ki", "i", "kie"),
  "telki" => array("ki", "je", "kie"), 
  "olki" => array("ki", "je", "kie"), 
  "solki" => array("ki", "je", "kie"), 
  "kylki" => array("ki", "je", "kie"),
  "sylki" => array("ki", "je", "kie"),
  "jälki" => array("ki", "je", "kie"), 
  "hanki" => array("ki", "ge", "kie"),
  "kanki" => array("ki", "ge", "kie"), 
  "vanki" => array("ki", "gi", "kie"),
  "henki" => array("ki", "ge", "kie"),
  "renki" => array("ki", "gi", "kie"),
  "killinki" => array("ki", "gi", "kie"),
  "onki" => array("ki", "ge", "kie"),
  "kuponki" => array("ki", "gi", "kie"),
  "sänki" => array("ki", "ge", "kie"),
  "joki" => array("ki", "e", "kie"), 
  "noki" => array("ki", "e", "kie"), 
  "arki" => array("ki", "je", "kie"),
  "kurki" => array("ki", "je", "kie"), 
  "järki" => array("ki", "je", "kie"),
  "kärki" => array("ki", "je", "kie"), 
  "särki" => array("ki", "je", "kie"),
  "kaski" => array("i", "e", "ie"), 
  "vaski" => array("i", "e", "ie"), 
  "leski" => array("i", "e", "kie"), 
  "kiiski" => array("i", "e", "ie"), 
  "viski" => array("i", "i", "ie"),
  "koski" => array("i", "e", "ie"), 
  "poski" => array("i", "e", "ie"), 
  "sääski" => array("i", "e", "ie"), 
  "hetki" => array("i", "e", "ie"), 
  "retki" => array("i", "e", "ie"), 
  "putki" => array("i", "e", "ie"), 
  "hauki" => array("ki", "e", "kie"), 
  "tuki" => array("ki", "e", "kie"), 
  "käki" => array("ki", "e", "kie"), 
  "mäki" => array("ki", "e", "kie"), 
  "väki" => array("ki", "e", "kie"),
  // -- li
  "banaali" => array("i", "i", "ie"),
  "kieli" => array("i", "e", "ie"), 
  "mieli" => array("i", "e", "ie"),
  "pieli" => array("i", "e", "ie"),
  "tunneli" => array("i", "i", "ie"),
  "peli" => array("i", "i", "ie"),
  "veli" => array("i", "je", "ie"), 
  "peili" => array("", "", "lie"),
  "symboli" => array("i", "i", "ie"),
  "pistooli" => array("i", "i", "ie"),
  "huoli" => array("i", "e", "ie"), 
  "nuoli" => array("i", "e", "ie"), 
  "puoli" => array("i", "e", "ie"),
  "suoli" => array("i", "e", "ie"), 
  "tuoli" => array("i", "i", "ie"),
  "sipuli" => array("i", "i", "ie"), 
  "konsuli" => array("i", "i", "eide"),
  "tuuli" => array("i", "e", "ie"),
  // -- mi
  "niemi" => array("mi", "me", "mie"),
  "seimi" => array("i", "e", "ie"), 
  "nimi" => array("i", "e", "ie"), 
  "salmi" => array("i", "e", "ie"), 
  "helmi" => array("i", "e", "ie"), 
  "filmi" => array("i", "i", "ie"),
  "tammi" => array("i", "e", "ie"), 
  "pommi" => array("i", "i", "ie"),
  "nummi" => array("i", "e", "ie"), 
  "suomi" => array("i", "e", "ie"),
  "tuomi" => array("mi", "me", "mie"),
  "karmi" => array("i", "i", "ie"),
  "sormi" => array("i", "e", "ie"), 
  "nurmi" => array("i", "e", "ie"), 
  "turismi" => array("i", "i", "ie"),
  "kumi" => array("i", "i", "ie"),
  "lumi" => array("mi", "me", "mie"),
  "kymi" => array("i", "e", "ie"),
  // -- ni
  "ääni" => array("i", "e", "ie"), 
  "tulppaani" => array("i", "i", "eide"),
  "kumppani" => array("i", "i", "eide"),
  "pieni" => array("i", "e", "ie"), 
  "sieni" => array("i", "e", "ie"), 
  "insuliini" => array("i", "i", "ie"),
  "niini" => array("i", "e", "ie"), 
  "viini" => array("i", "i", "ie"), // not nuoliviini
  "sini" => array("i", "e", "ie"), 
  "onni" => array("i", "e", "ie"), 
  "ränni" => array("i", "i", "ie"), 
  "telefoni" => array("ni", "ni", "nie"),
  "kortisoni" => array("i", "i", "eide"),
  "betoni" => array("", "", "nie"),
  "juoni" => array("i", "e", "ie"), 
  "suoni" => array("i", "e", "ie"), 
  "tuoni" => array("i", "e", "ie"), 
  "saarni" => array("i", "e", "ie"), 
  "torni" => array("", "", "nie"),
  "uni" => array("i", "e", "ie"), 
  "tyyni" => array("i", "e", "ie"), 
  // -- pi
  "siipi" => array("pi", "ve", "pie"), 
  "koipi" => array("pi", "ve", "pie"), 
  "alpi" => array("i", "e", "ie"), 
  "helpi" => array("pi", "ve", "pie"), 
  "kilpi" => array("pi", "ve", "pie"),
  "lampi" => array("pi", "me", "pie"),
  "sampi" => array("pi", "me", "pie"), 
  "lempi" => array("pi", "me", "pie"), 
  "suurempi" => array("mpi", "mma", "mpie"),
  "impi" => array("pi", "me", "pie"), 
  "kimpi" => array("pi", "me", "pie"), 
  "rimpi" => array("pi", "me", "pie"), 
  "umpi" => array("pi", "me", "pimie"), 
  "kumpi" => array("pi", "ma", "pie"),
  "appi" => array("pi", "e", "pie"),
  "happi" => array("pi", "e", "pie"), 
  "sinappi" => array("pi", "i", "pie"),
  "sappi" => array("pi", "e", "pie"), 
  "keppi" => array("pi", "i", "pie"),
  "oppi" => array("pi", "i", "pie"),
  "soppi" => array("pi", "e", "pie"), 
  "kuppi" => array("pi", "i", "pie"), 
  "tuppi" => array("pi", "e", "pie"), 
  "typpi" => array("pi", "e", "pie"), 
  "tyyppi" => array("pi", "i", "pie"), 
  "arpi" => array("pi", "ve", "pie"),
  "virpi" => array("pi", "ve", "pie"), 
  "korpi" => array("pi", "ve", "pie"), 
  "hupi" => array("pi", "vi", "pie"),
  "rupi" => array("pi", "ve", "pie"), 
  "läpi" => array("pi", "ve", "pie"), 
  // -- ri
  "aari" => array("i", "i", "ie"),
  "kaari" => array("i", "e", "ie"), 
  "saari" => array("i", "e", "ie"),
  "sankari" => array("i", "i", "eide"),
  "naamari" => array("i", "i", "ie"),
  "tuomari" => array("i", "i", "eide"),
  "kamari" => array("mari", "mmari", "marie"),
  "teeri" => array("i", "e", "ie"),
  "bakteeri" => array("i", "i", "ie"),
  "terrieri" => array("i", "i", "eide"), 
  "vieri" => array("i", "e", "ie"), 
  "summeri" => array("i", "i", "eide"),
  "paperi" => array("i", "i", "ie"),
  "veri" => array("i", "e", "ie"), 
  "toveri" => array("i", "i", "ie"), 
  "hiiri" => array("i", "e", "ie"), 
  "ori" => array("i", "ii", "iitte"),
  "kori" => array("i", "i", "ie"),
  "kuori" => array("i", "e", "ie"), 
  "nuori" => array("i", "e", "ie"), 
  "vuori" => array("i", "e", "ie"), // mountain - not coat of jacket vuori
  "peluri" => array("i", "i", "eide"),
  "kuuri" => array("i", "i", "ie"), 
  "juuri" => array("i", "e", "ie"), 
  "suuri" => array("i", "e", "ie"),
  "sääri" => array("i", "e", "ie"),
  // -- si
  "paasi" => array("si", "de", "sie"),
  "lasi" => array("i", "i", "ie"),
  "desi" => array("i", "i", "ie"),
  "liesi" => array("si", "de", "sie"),
  "kesi" => array("si", "de", "sie"),
  "mesi" => array("si", "de", "sie"),
  "vesi" => array("si", "de", "sie"),
  "heisi" => array("i", "e", "ie"), 
  "reisi" => array("si", "de", "sie"),
  "poliisi" => array("i", "i", "ie"),
  "hiisi" => array("i", "e", "ie"), 
  "niisi" => array("si", "de", "sie"),
  "saksi" => array("i", "e", "ie"), 
  "viiksi" => array("i", "e", "ie"), 
  "vuoksi" => array("i", "e", "ie"),
  "uksi" => array("i", "e", "ie"), 
  "suksi" => array("i", "e", "ie"), 
  "sääksi" => array("i", "e", "ie"), 
  "jälsi" => array("si", "le", "sie"),
  "kansi" => array("si", "ne", "sie"),
  "loosi" => array("", "", "sie"),
  "tosi" => array("si", "de", "sie"),
  "vuosi" => array("si", "de", "sie"),
  "hapsi" => array("i", "e", "ie"), 
  "lapsi" => array("si", "se", "sie"),
  "ripsi" => array("i", "e", "ie"), 
  "hirsi" => array("si", "re", "sie"),
  "peitsi" => array("si", "se", "sie"),
  "veitsi" => array("i", "e", "ie"), 
  "ruotsi" => array("i", "i", "ie"),
  "kvartsi" => array("i", "i", "ie"),
  "kausi" => array("si", "de", "ie"),
  "jousi" => array("i", "e", "ie"), 
  "susi" => array("si", "de", "sie"),
  "uusi" => array("si", "de", "sie"), 
  "kuusi" => array("si", "se", "sie"), // tree not a number
  "sysi" => array("si", "de", "sie"),
  "täysi" => array("si", "de", "sie"),
  "köysi" => array("si", "de", "sie"),
  "käsi" => array("si", "de", "sie"),
  // -- ti
  "vati" => array("ti", "di", "tie"),
  "peti" => array("ti", "di", "tie"),
  "haahti" => array("ti", "de", "tie"), 
  "lahti" => array("ti", "de", "tie"), 
  "vahti" => array("ti", "di", "tie"),
  "lehti" => array("ti", "de", "tie"),
  "konvehti" => array("ti", "di", "tie"),
  "pihti" => array("ti", "di", "tie"),
  "vyyhti" => array("ti", "de", "tie"), 
  "tähti" => array("ti", "de", "tie"),
  "neiti" => array("ti", "di", "tie"),
  "äiti" => array("ti", "di", "tie"),
  "pelti" => array("ti", "li", "tie"),
  "hollanti" => array("ti", "ni", "ie"),
  "tunti" => array("ti", "ni", "tie"),
  "koti" => array("ti", "di", "tie"),
  "siisti" => array("i", "i", "ie"),
  "risti" => array("ti", "ti", "tie"),
  "salaatti" => array("ti", "i", "tie"),
  "tatti" => array("ti", "i", "tie"),
  "tauti" => array("ti", "di", "tie"),
  // -- vi
  "savi" => array("i", "e", "ie"), 
  "substantiivi" => array("i", "i", "ie"),
  "kivi" => array("i", "e", "ie"), 
  "palvi" => array("i", "e", "ie"), 
  "talvi" => array("i", "e", "ie"), 
  "pilvi" => array("i", "e", "ie"), 
  "polvi" => array("i", "e", "ie"), 
  "pälvi" => array("i", "e", "ie"), 
  "ovi" => array("i", "e", "ie"), 
  "alkovi" => array("i", "i", "ie"),
  "lovi" => array("i", "e", "ie"), 
  "povi" => array("i", "e", "ie"), 
  "muovi" => array("i", "i", "ie"),
  "parvi" => array("i", "e", "ie"), 
  "sarvi" => array("i", "e", "ie"), 
  "hirvi" => array("i", "e", "ie"), 
  "torvi" => array("i", "e", "ie"), 
  "järvi" => array("i", "e", "ie"), 
  "kasvi" => array("i", "i", "ie"),
  "huvi" => array("i", "i", "ie"),
  "suvi" => array("i", "e", "ie"),
  "tyvi" => array("i", "e", "ie"), 
  // -- ak
  "teak" => array("k", "ki", "kie"),
  // -- ck
  "rock" => array("k", "ki", "kie"),
  // -- nk
  "punk" => array("k", "ki", "kie"),
  // -- al
  "sammal" => array("l", "lee", "leide"),
  "taival" => array("val", "palee", "paleide"),
  // -- el
  "askel" => array("l", "lee", "lte"),
  "ommel" => array("mel", "pelee", "peleide"),
  "kannel" => array("nel", "telee", "teleide"),
  "opel" => array("l", "li", "lie"),
  // -- am
  "edam" => array("m", "mi", "mie"),
  // -- um
  "kalsium" => array("m", "mi", "mie"),
  // -- an
  "fan" => array("n", "ni", "nie"),
  "hapan" => array("an", "pame", "pamie"),
  "kahdeksan" => array("an", "a", "ie"),
  "muuan" => array("an", "tama", "tamie"),
  // -- en
  "siemen" => array("n", "ne", "nie"),
  "nainen" => array("nen", "se", "sie"),
  "punainen" => array("inen", "ise", "ste"),
  "topografinen" => array("finen", "fise", "fisie"),
  "filosofinen" => array("finen", "fise", "fisie"),
  "psykologinen" => array("ginen", "gise", "gisie"),
  "psyykkinen" => array("kinen", "kise", "kiste"),
  "ironinen" => array("nen", "se", "sie"),
  "eeppinen" => array("pinen", "pise", "piste"),
  "allegorinen" => array("rinen", "rise", "risie"),
  "kriittinen" => array("tinen", "tise", "tiste"),
  "relatiivinen" => array("nen", "se", "ste"),
  "hevonen" => array("nen", "se", "sie"),
  "vasen" => array("n", "mma", "mpie"),
  "ahven" => array("n", "ne", "nie"),
  "säen" => array("en", "kene", "keneide"),
  "puoleen" => array("en", "ise", "iste"),
  "rauhanen" => array("nen", "se", "ste"),
  "ien" => array("en", "kene", "kenie"),
  // -- in
  "kasvain" => array("in", "ime", "imie"),
  "kaadin" => array("din", "time", "timie"),
  "pahin" => array("in", "imma", "impie"),
  "poljin" => array("jin", "kime", "kimie"),
  "elin" => array("n", "me", "mie"),
  "sivellin" => array("lin", "time", "timie"),
  "lämmin" => array("min", "pimä", "pimie"),
  "vaimennin" => array("nin", "time", "timie"),
  "kerroin" => array("roin", "toime", "toimie"),
  "kiharrin" => array("rin", "time", "timie"),
  "sisin" => array("in", "ime", "imie"),
  "suodatin" => array("in", "time", "timie"),
  "kuljetin" => array("in", "time", "timie"),
  "teroitin" => array("in", "time", "timie"),
  "uistin" => array("n", "me", "mie"),
  "sumutin" => array("in", "time", "timie"),
  "puin" => array("in", "kime", "kimie"),
  "istuin" => array("n", "me", "mie"),
  "kaavin" => array("vin", "pime", "pimie"),
  // -- on
  "stadion" => array("n", "ni", "ide"),
  "onneton" => array("on", "toma", "tomie"),
  "alaston" => array("n", "ma", "mie"),
  // -- un
  "laidun" => array("dun", "tume", "tumie"),
  // -- än
  "sydän" => array("n", "mme", "mmie"),
  "hän" => array("än", "äne", "eidä"),
  // -- eo
  "video" => array("o", "o", "oide"),
  // -- io
  "illuusio" => array("o", "o", "oide"),
  "obligaatio" => array("o", "o", "oide"),
  "traditio" => array("o", "o", "oide"),
  "funktio" => array("o", "o", "oide"),
  "autio" => array("o", "o", "oide"),
  "resoluutio" => array("o", "o", "oide"),
  // -- ko
  "rako" => array("ko", "o", "koje"),
  "teko" => array("ko", "o", "koje"),
  "vihko" => array("ko", "o", "koje"),
  "laatikko" => array("ko", "o", "oide"),
  "verkko" => array("ko", "o", "koje"),
  "halko" => array("ko", "o", "koje"),
  "hanko" => array("ko", "go", "koje"),
  "alanko" => array("ko", "go", "koje"),
  "koko" => array("ko", "o", "koje"),
  "ruoko" => array("ko", "'o", "koje"),
  "usko" => array("o", "o", "oje"),
  // -- lo
  "valo" => array("o", "o", "oje"),
  "hontelo" => array("lo", "lo", "loide"),
  // -- no
  "pano" => array("no", "no", "noje"),
  // -- oo
  "trikoo" => array("o", "", "ide"),
  "tienoo" => array("o", "o", "ide"),
  // -- po
  "lepo" => array("po", "vo", "poje"),
  "sampo" => array("po", "mo", "poje"),
  "mopo" => array("po", "po", "poje"),
  "kippo" => array("po", "o", "poje"),
  // -- ro
  "numero" => array("o", "o", "oide"),
  // -- to
  "pato" => array("to", "do", "toje"),
  "tieto" => array("to", "do", "toje"),
  "johto" => array("to", "do", "toje"),
  "taito" => array("to", "do", "toje"),
  "aalto" => array("to", "lo", "toje"),
  "anto" => array("to", "no", "toje"),
  "avanto" => array("to", "no", "toje"),
  "muoto" => array("to", "do", "toje"),
  "kaarto" => array("to", "ro", "toje"),
  "koneisto" => array("o", "o", "oide"),
  "aarteisto" => array("isto", "histo", "istoide"),
  "pihatto" => array("to", "o", "toje"),
  "liitto" => array("to", "o", "toje"),
  "auto" => array("o", "o", "oje"),
  "leuto" => array("to", "do", "toje"),
  // -- uo
  "suo" => array("uo", "uo", "oide"),
  // -- op
  "pop" => array("p", "pi", "pie"),
  // -- ar
  "maar" => array("r", "ri", "rie"),
  "udar" => array("dar", "taree", "tareide"),
  "piennar" => array("nar", "taree", "tareide"),
  "sisar" => array("r", "re", "rie"),
  // -- er
  "penger" => array("ger", "keree", "kereide"),
  "kinner" => array("ner", "teree", "tereide"),
  "auer" => array("er", "teree", "tereitte"),
  // -- är
  "tytär" => array("är", "täre", "tärie"),
  // -- as
  "ahdas" => array("das", "taa", "taide"),
  "kangas" => array("gas", "kaa", "kaide"),
  "lihas" => array("s", "kse", "ksie"),
  "antelias" => array("s", "a", "ide"),
  "utelias" => array("s", "a", "ide"),
  "laupias" => array("ias", "iaa", "iaide"),
  "rakas" => array("as", "kaa", "kaide"),
  "maineikas" => array("as", "kaa", "kaide"),
  "raskas" => array("s", "a", "ide"),
  "valas" => array("s", "a", "ide"),
  "sotilas" => array("s", "a", "ide"),
  "allas" => array("las", "taa", "taide"),
  "hammas" => array("mas", "paa", "paide"),
  "ananas" => array("s", "kse", "ksie"),
  "kinnas" => array("nas", "taa", "taide"),
  "saapas" => array("as", "paa", "paide"),
  "paras" => array("as", "haa", "haide"),
  "varas" => array("as", "kaa", "kaide"),
  "vieras" => array("s", "a", "ide"),
  "koiras" => array("s", "a", "ide"),
  "harras" => array("ras", "taa", "taide"),
  "kahdeksas" => array("s", "nne", "nsie"),
  "porsas" => array("s", "a", "ide"),
  "ratas" => array("as", "taa", "taide"),
  "kiuas" => array("as", "kaa", "kaide"),
  "autuas" => array("as", "aa", "aide"),
  "varvas" => array("vas", "paa", "paide"),
  // -- es
  "ies" => array("es", "kee", "keide"),
  "mies" => array("s", "he", "hie"),
  "bisnes" => array("s", "kse", "ksie"),
  "kirves" => array("s", "e", "ide"),
  // -- is
  "julkkis" => array("is", "ikse", "iksie"),
  "valmis" => array("is", "ii", "iide"),
  "kaunis" => array("is", "ii", "iide"),
  "kauris" => array("is", "ii", "iide"),
  "raitis" => array("is", "tii", "tiide"),
  "altis" => array("is", "tii", "tiide"),
  "ruis" => array("is", "kii", "kiide"),
  // -- os
  "uros" => array("s", "kse", "ksie"),
  // -- us
  "vapaus" => array("s", "de", "ksie"),
  "ohjaus" => array("s", "kse", "ksie"),
  "pakkaus" => array("s", "kse", "ksie"),
  "rakkaus" => array("s", "de", "ksie"), // exception on akkaus conjugation
  "leikkaus" => array("s", "kse", "ksie"),
  "purkaus" => array("s", "kse", "ksie"),
  "raskaus" => array("s", "de", "ksie"),
  "taklaus" => array("s", "kse", "ksie"),
  "kaipaus" => array("s", "kse", "ksie"),
  "toppaus" => array("s", "kse", "ksie"),
  "lupaus" => array("s", "kse", "ksie"),
  "runsaus" => array("s", "de", "ksie"),
  "katsaus" => array("s", "kse", "ksie"),
  "kiusaus" => array("s", "kse", "ksie"),
  "vastaus" => array("s", "kse", "ksie"),
  "pilkahdus" => array("s", "kse", "ksie"),
  "kalleus" => array("s", "de", "ksie"),
  "ohjus" => array("s", "kse", "ksie"),
  "keskus" => array("s", "kse", "ksie"),
  "kaulus" => array("s", "kse", "ksie"),
  "kertomus" => array("s", "kse", "ksie"),
  "rakennus" => array("s", "kse", "ksie"),
  "tarjous" => array("s", "kse", "ksie"),
  "heikkous" => array("s", "de", "ksie"),
  "kokous" => array("s", "kse", "ksie"),
  "talous" => array("s", "de", "ksie"),
  "vierus" => array("s", "kse", "ksie"),
  "aivoitus" => array("s", "kse", "ksie"),
  "jaotus" => array("s", "kse", "ksie"),
  // -- ys
  "yhteys" => array("s", "de", "ksie"),
  "pysähdys" => array("s", "kse", "ksie"),
  "kyljys" => array("s", "kse", "ksie"),
  "päälys" => array("s", "kse", "ksie"),
  "väsymys" => array("s", "kse", "ksie"),
  "kypsennys" => array("s", "kse", "ksie"),
  "lämmitys" => array("s", "kse", "ksie"),
  "määräys" => array("s", "kse", "ksie"),
  // -- äs
  "iäkäs" => array("äs", "kää", "käide"),
  "teräs" => array("s", "kse", "ksie"),
  "pylväs" => array("s", "ä", "ide"),
  // -- et
  "alkeet" => array("et", "ide", "ide"),
  "harteet" => array("et", "itte", "itte"),
  "länget" => array("get", "ge", "kie"), 
  "suitset" => array("et", "ie", "ie"),
  "päitset" => array("et", "e", "ie"), 
  // -- it
  "parfait" => array("", "'", "e"),
  "pihdit" => array("dit", "tie", "tie"),
  "tanssit" => array("t", "e", "e"),
  // -- ot
  "aivot" => array("ot", "oje", "oje"),
  // -- ut
  "kuollut" => array("lut", "lee", "leide"),
  "punonut" => array("nut", "nee", "neide"),
  "airut" => array("t", "e", "eide"),
  "purrut" => array("rut", "ree", "reide"),
  "juossut" => array("sut", "see", "seide"),
  // -- yt
  "pöksyt" => array("yt", "yje", "yje"),
  "neitsyt" => array("yt", "ye", "yeide"),
  // -- ät
  "kevät" => array("t", "ä", "ide"),
  // -- iu
  "tiu" => array("u", "u", "u"),
  // -- ku
  "haku" => array("ku", "u", "kuje"),
  "laku" => array("u", "u", "uje"),
  "maku" => array("ku", "u", "kuje"),
  "suihku" => array("u", "u", "uje"),
  "kinkku" => array("ku", "u", "kuje"),
  "alku" => array("ku", "u", "kuje"),
  "hinku" => array("ku", "gu", "kuje"),
  "ruisku" => array("u", "u", "uje"),
  "luku" => array("ku", "vu", "kuje"),
  "tiuku" => array("ku", "'u", "kuje"),
  // -- lu
  "arvelu" => array("u", "u", "uide"),
  "taulu" => array("u", "u", "uje"),
  // -- nu
  "gnu" => array("u", "u", "uide"),
  // -- pu
  "apu" => array("pu", "vu", "puje"),
  "kumpu" => array("pu", "mu", "puje"),
  "hoppu" => array("pu", "u", "puje"),
  // -- ru
  "kiiru" => array("ru", "ruu", "reide"),
  "piru" => array("ru", "ru", "ruje"),
  "koru" => array("u", "u", "uje"),
  // -- tu
  "laatu" => array("tu", "du", "tuje"),
  "kohtu" => array("tu", "du", "tuje"),
  "kuitu" => array("tu", "du", "tuje"),
  "katseltu" => array("tu", "lu", "tuje"),
  "oltu" => array("tu", "lu", "tuje"),
  "lintu" => array("tu", "nu", "tuje"),
  "rotu" => array("tu", "du", "tuje"),
  "purtu" => array("tu", "ru", "tuje"),
  "nuolaistu" => array("tu", "tu", "tuje"),
  "hattu" => array("tu", "u", "tuje"),
  "raamattu" => array("tu", "u", "tuje"),
  "puhuttu" => array("tu", "u", "tuje"),
  "seutu" => array("tu", "du", "tuje"),
  // -- uu
  "leikkuu" => array("u", "u", "uksie"),
  "puu" => array("u", "u", "ide"),
  // -- ay
  "spray" => array("y", "y", "yide"),
  // -- ky
  "myrkky" => array("ky", "y", "kyje"),  
  "hylky" => array("ky", "y", "kyje"),
  "sänky" => array("ky", "gy", "kyje"),  
  "myrsky" => array("y", "y", "yje"),
  "kyky" => array("ky", "vy", "kyje"),  
  // -- py
  "kylpy" => array("py", "vy", "pyje"),  
  "hyppy" => array("py", "y", "pyje"),
  // -- ty
  "lyhty" => array("ty", "dy", "tyje"),  
  "synty" => array("ty", "ny", "tyje"),  
  "yhdistetty" => array("ty", "y", "tyje"),  
  // -- yy
  "revyy" => array("y", "y", "ide"),
  // -- ä
  "myyjä" => array("jä", "jä", "jie"),
  "ikä" => array("kä", "ä", "kie"),
  "reikä" => array("kä", "ä", "kie"),
  "selkä" => array("kä", "ä", "kie"),
  "ylkä" => array("kä", "jä", "kie"),
  "härkä" => array("kä", "ä", "kie"),
  "pitkä" => array("ä", "ä", "ie"),
  "keväämmällä" => array("lä", "lä", "leide"),
  "minä" => array("inä", "inu", "eidä"),
  "sinä" => array("sinä", "sinun", "teidä"),
  "leipä" => array("pä", "vä", "pie"),
  "emäntä" => array("tä", "nä", "tie"),
  "kenttä" => array("tä", "ä", "tie"),
  "pöytä" => array("tä", "dä", "tie"),
  // -- ö
  "sähkö" => array("ö", "ö", "öje"),
  "kätkö" => array("ö", "ö", "öje"),
  "kiinteistö" => array("tö", "tö", "töjen"),
  "enemmistö" => array("ö", "ö", "öide"),
  "löytö" => array("tö", "dö", "töje"),
  "yö" => array("yö", "yö", "öide"),

);