<?php
/**
* what gets replaced with what in what conjugation
* fex. "huopa" => array("pa", "si" => array("va", "va"), "pl" => array("pie", "vi")),
* genitive => huo va n ["si"][0]
* translative => huo va ksi ["si"][1]
* plural => huo va t ["si"][0]
* plural genitive => huo pie n ["pl"][0]
* plural translative => huo vi ksi ["pl"][1]
*
* words are reverse sorted with some reorganizing as the best match is picked first
* fex. we have 2 akkaus words. First the more common version and then the exception
*  "pakkaus" => array("s", "kse", "ksie"), // same as hakkaus, sakkaus, kakkaus, lakkaus
*  "rakkaus" => array("s", "de", "ksie"), // the exception
*
*/

$words = array(
  // -- aa
  "nugaa" => array("a", "si" => array("a", "a"), "pl" => array("ide", "i")),
  "maa" => array("a", "si" => array("a", "a"), "pl" => array("ide", "ailmo")),
  "vapaa" => array("a", "si" => array("a", "a"), "pl" => array("ide", "i")),
  "sataa" => array("taa", "si" => array("danne", "danne"), "pl" => array("dansie", "dansi")),
  // -- ea
  "korkea" => array("a", "si" => array("a", "a"), "pl" => array("ide", "i")),
  // -- ia
  "topografia" => array("a", "si" => array("a", "a"), "pl" => array("oide", "oi")),
  "filosofia" => array("a", "si" => array("a", "a"), "pl" => array("oide", "oi")),
  "analogia" => array("a", "si" => array("a", "a"), "pl" => array("oide", "oi")),
  // -- ja
  "apaja" => array("a", "si" => array("a", "a"), "pl" => array("oide", "oi")),
  "kantaja" => array("a", "si" => array("a", "a"), "pl" => array("ie", "i")),
  "kulkija" => array("a", "si" => array("a", "a"), "pl" => array("oide", "oi")),
  "oja" => array("a", "si" => array("a", "a"), "pl" => array("ie", "i")),
  // -- ka
  "raaka" => array("ka", "si" => array("'a", "'a"), "pl" => array("koje", "oi")),
  "haka" => array("ka", "si" => array("a", "a"), "pl" => array("koje", "oi")),
  "nahka" => array("ka", "si" => array("a", "a"), "pl" => array("koje", "oi")),
  "karahka" => array("a", "si" => array("a", "a"), "pl" => array("oje", "oi")),
  "aika" => array("ika", "si" => array("ja", "ja"), "pl" => array("ikoje", "joi")),
  "liika" => array("ka", "si" => array("a", "a"), "pl" => array("koje", "a")),
  "poika" => array("ika", "si" => array("ja", "ja"), "pl" => array("ikie", "ji")),
  "sika" => array("ka", "si" => array("a", "a"), "pl" => array("koje", "oi")),
  "solakka" => array("ka", "si" => array("a", "a"), "pl" => array("oide", "oi")),
  "hoikka" => array("ka", "si" => array("a", "a"), "pl" => array("kie", "i")),
  "hanka" => array("ka", "si" => array("ga", "ga"), "pl" => array("koje", "goi")),
  "honka" => array("ka", "si" => array("ga", "ga"), "pl" => array("kie", "gi")),
  "joka" => array("ka", "si" => array("nka", "nka"), "pl" => array("ide", "i")),
  "ruoka" => array("oka", "si" => array("oa", "oa"), "pl" => array("okie", "ui")),
  // -- la
  "kala" => array("a", "si" => array("a", "a"), "pl" => array("oje", "oi")),
  "jumala" => array("a", "si" => array("a", "a"), "pl" => array("ie", "i")),
  "matala" => array("a", "si" => array("a", "a"), "pl" => array("ie", "i")),
  "apila" => array("a", "si" => array("a", "a"), "pl" => array("oide", "oi")),
  "loitolla" => array("la", "si" => array("lamma", "lamma"), "pl" => array("lammaide", "lammi")),
  // -- ma
  "asema" => array("a", "si" => array("a", "a"), "pl" => array("ie", "i")),
  "voima" => array("ma", "si" => array("ma", "ma"), "pl" => array("mie", "mi")),
  // -- na
  "sivumpana" => array("pana", "si" => array("ma", "ma"), "pl" => array("mie", "mi")),
  "markkina" => array("a", "si" => array("a", "a"), "pl" => array("oide", "oi")),
  "peruna" => array("a", "si" => array("a", "a"), "pl" => array("oide", "oi")),
  "pasuuna" => array("a", "si" => array("a", "a"), "pl" => array("oide", "i")),
  // -- oa
  "ainoa" => array("a", "si" => array("o", "o"), "pl" => array("ide", "i")),
  // -- pa
  "napa" => array("pa", "si" => array("va", "va"), "pl" => array("poje", "voi")),
  "halpa" => array("pa", "si" => array("va", "va"), "pl" => array("poje", "voi")),
  "kampa" => array("pa", "si" => array("ma", "ma"), "pl" => array("poje", "moi")),
  "kompa" => array("pa", "si" => array("ma", "ma"), "pl" => array("pie", "mi")),
  "huopa" => array("pa", "si" => array("va", "va"), "pl" => array("pie", "vi")),
  "kappa" => array("pa", "si" => array("a", "a"), "pl" => array("poje", "oi")),
  "ulappa" => array("pa", "si" => array("a", "a"), "pl" => array("oide", "oi")),
  "tolppa" => array("pa", "si" => array("a", "a"), "pl" => array("pie", "i")),
  "lupa" => array("pa", "si" => array("va", "va"), "pl" => array("pie", "vi")),
  // -- ra
  "makkara" => array("a", "si" => array("a", "a"), "pl" => array("oide", "oi")),
  "koira" => array("a", "si" => array("a", "a"), "pl" => array("ie", "i")),
  // -- sa
  "kisa" => array("sa", "si" => array("sa", "sa"), "pl" => array("soje", "oi")),
  // -- ta
  "pata" => array("ta", "si" => array("da", "da"), "pl" => array("toje", "doi")),
  "juhta" => array("ta", "si" => array("da", "da"), "pl" => array("tie", "di")),
  "riita" => array("ta", "si" => array("da", "da"), "pl" => array("toje", "doi")),
  "valta" => array("ta", "si" => array("la", "la"), "pl" => array("toje", "loi")),
  "kulta" => array("ta", "si" => array("la", "la"), "pl" => array("tie", "li")),
  "vihanta" => array("ta", "si" => array("na", "na"), "pl" => array("toje", "ni")),
  "kanta" => array("ta", "si" => array("na", "na"), "pl" => array("toje", "noi")),
  "veranta" => array("ta", "si" => array("na", "na"), "pl" => array("tie", "ni")),
  "suunta" => array("ta", "si" => array("na", "na"), "pl" => array("tie", "ni")),
  "kota" => array("ta", "si" => array("da", "da"), "pl" => array("tie", "di")),
  "parta" => array("ta", "si" => array("ra", "ra"), "pl" => array("toje", "roi")),
  "turta" => array("ta", "si" => array("ra", "ra"), "pl" => array("tie", "ri")),
  "alusta" => array("a", "si" => array("a", "a"), "pl" => array("oje", "i")),
  "aitta" => array("ta", "si" => array("a", "a"), "pl" => array("toje", "oi")),
  "savotta" => array("ta", "si" => array("a", "a"), "pl" => array("oide", "oi")),
  "pouta" => array("ta", "si" => array("da", "da"), "pl" => array("tie", "di")),
  // -- ua
  "herttua" => array("ua", "si" => array("ua", "ua"), "pl" => array("uoide", "uoi")),
  // -- ab
  "kebab" => array("b", "si" => array("bi", "bi"), "pl" => array("bie", "bie")),
  // -- rc
  "farc" => array("c", "si" => array("ci", "ci"), "pl" => array("cie", "cie")),
  // -- nd
  "band" => array("d", "si" => array("di", "di"), "pl" => array("die", "die")),
  // -- ae
  "tae" => array("e", "si" => array("kee", "kee"), "pl" => array("keide", "kei")),
  // -- be
  "bebe" => array("e", "si" => array("e", "e"), "pl" => array("eide", "ei")),
  // -- de
  "sade" => array("de", "si" => array("tee", "tee"), "pl" => array("teide", "tei")),
  // -- ee
  "tee" => array("e", "si" => array("e", "e"), "pl" => array("ide", "i")),
  // -- ge
  "college" => array("e", "si" => array("e", "e"), "pl" => array("eide", "ei")),
  // -- he
  "pahe" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  // -- ie
  "aie" => array("e", "si" => array("kee", "kee"), "pl" => array("keide", "kei")),
  "tie" => array("ie", "si" => array("ie", "ie"), "pl" => array("eide", "ei")),
  // -- je
  "lahje" => array("je", "si" => array("kee", "kee"), "pl" => array("keide", "kei")),
  "ohje" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  "purje" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  // -- ke
  "eläke" => array("e", "si" => array("kee", "kee"), "pl" => array("keide", "kei")),
  "tarvike" => array("e", "si" => array("kee", "kee"), "pl" => array("keide", "kei")),
  "suihke" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  "nukke" => array("ke", "si" => array("e", "e"), "pl" => array("keje", "kei")),
  // -- le
  "suikale" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  "nalle" => array("e", "si" => array("e", "e"), "pl" => array("eje", "ei")),
  "helle" => array("le", "si" => array("tee", "tee"), "pl" => array("teide", "tei")),
  "joule" => array("e", "si" => array("e", "e"), "pl" => array("eide", "ei")),
  // -- me
  "hame" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  "amme" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  "lumme" => array("me", "si" => array("pee", "pee"), "pl" => array("peide", "pei")),
  "käärme" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  "me" => array("e", "si" => array("eidä", "eidä"), "pl" => array("eitte", "ei")),
  // -- ne
  "aine" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  "akne" => array("e", "si" => array("e", "e"), "pl" => array("eje", "ei")),
  "enne" => array("ne", "si" => array("tee", "tee"), "pl" => array("teide", "tei")),
  // -- oe
  "koe" => array("e", "si" => array("kee", "kee"), "pl" => array("keide", "kei")),
  // -- pe
  "lape" => array("e", "si" => array("pee", "pee"), "pl" => array("peide", "pei")),
  // -- re
  "utare" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  "vire" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  "kierre" => array("re", "si" => array("tee", "tee"), "pl" => array("teide", "teide")),
  // -- se
  "ase" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  "rose" => array("e", "si" => array("e", "e"), "pl" => array("eide", "ei")),
  // -- te
 // "vaate" => array("e", "si" => array("tee", "tee"), "pl" => array("teide", "teide")),
  "näyte" => array("te", "si" => array("ttee", "ttee"), "pl" => array("tteide", "ttei")),
  "raaste" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  "raglette" => array("te", "si" => array("e", "e"), "pl" => array("teide", "teide")),
  "liete" => array("te", "si" => array("ttee", "ttee"), "pl" => array("tteide", "ttei")),
  "osoite" => array("te", "si" => array("ttee", "ttee"), "pl" => array("tteide", "ttei")),
  "polte" => array("te", "si" => array("ttee", "ttee"), "pl" => array("tteide", "ttei")),
  "tiedote" => array("te", "si" => array("ttee", "ttee"), "pl" => array("tteide", "ttei")),
  "palaute" => array("te", "si" => array("ttee", "ttee"), "pl" => array("tteide", "ttei")),
  // -- ue
  "alue" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  // -- ve
  "taive" => array("ve", "si" => array("pee", "pee"), "pl" => array("peide", "pei")),
  "viive" => array("ve", "si" => array("pee", "pee"), "pl" => array("veide", "vei")),
  "tarve" => array("ve", "si" => array("pee", "pee"), "pl" => array("peide", "pei")),
  "terve" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  "katve" => array("ve", "si" => array("vee", "vee"), "pl" => array("veide", "vei")),
  // -- ye
  "yhtye" => array("e", "si" => array("ee", "ee"), "pl" => array("eide", "ei")),
  // -- lf
  "golf" => array("f", "si" => array("fi", "fi"), "pl" => array("fie", "fei")),
  // -- ng
  "doping" => array("g", "si" => array("gi", "gi"), "pl" => array("gie", "gie")),
  // -- ah
  "leah" => array("h", "si" => array("hi", "hi"), "pl" => array("hie", "hie")),
  // -- di
  "balladi" => array("i", "si" => array("i", "i"), "pl" => array("eide", "ei")),
  "marinadi" => array("adi", "si" => array("adi", "adi"), "pl" => array("adie", "ei")),
  "pyramidi" => array("idi", "si" => array("idi", "idi"), "pl" => array("idie", "ei")),
  // -- fi
  "biografi" => array("afi", "si" => array("afi", "afi"), "pl" => array("afie", "afie")),
  // -- hi
  "kaihi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "tilhi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "hanhi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "karhi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "kärhi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "närhi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  // -- ii
  "pii" => array("i", "si" => array("i", "i"), "pl" => array("ide", "i")),
  // -- ki
  "laki" => array("ki", "si" => array("e", "e"), "pl" => array("kie", "ei")),
  "reki" => array("ki", "si" => array("e", "e"), "pl" => array("kie", "ki")),
  "hiki" => array("ki", "si" => array("e", "e"), "pl" => array("kie", "ei")),
  "piki" => array("ki", "si" => array("e", "e"), "pl" => array("kie", "ei")),
  "kajakki" => array("ki", "si" => array("i", "i"), "pl" => array("kie", "ei")),
  "takki" => array("ki", "si" => array("i", "i"), "pl" => array("kie", "ei")),
  "kaikki" => array("ki", "si" => array("e", "e"), "pl" => array("kie", "i")),
  "leikki" => array("ki", "si" => array("i", "i"), "pl" => array("kie", "i")),
  "telki" => array("ki", "si" => array("je", "je"), "pl" => array("kie", "ji")),
  "olki" => array("ki", "si" => array("je", "je"), "pl" => array("kie", "ji")),
  "solki" => array("ki", "si" => array("je", "je"), "pl" => array("kie", "ji")),
  "kylki" => array("ki", "si" => array("je", "je"), "pl" => array("kie", "ji")),
  "sylki" => array("ki", "si" => array("je", "je"), "pl" => array("kie", "ji")),
  "jälki" => array("ki", "si" => array("je", "je"), "pl" => array("kie", "ji")),
  "hanki" => array("ki", "si" => array("ge", "ge"), "pl" => array("kie", "gi")),
  "kanki" => array("ki", "si" => array("ge", "ge"), "pl" => array("kie", "gi")),
  "vanki" => array("ki", "si" => array("gi", "gi"), "pl" => array("kie", "gei")),
  "henki" => array("ki", "si" => array("ge", "ge"), "pl" => array("kie", "gi")),
  "renki" => array("ki", "si" => array("gi", "gi"), "pl" => array("kie", "gi")),
  "killinki" => array("ki", "si" => array("gi", "gi"), "pl" => array("kie", "kei")),
  "onki" => array("ki", "si" => array("ge", "ge"), "pl" => array("kie", "gi")),
  "kuponki" => array("ki", "si" => array("gi", "gi"), "pl" => array("kie", "gei")),
  "sänki" => array("ki", "si" => array("ge", "ge"), "pl" => array("kie", "gi")),
  "joki" => array("ki", "si" => array("e", "e"), "pl" => array("kie", "i")),
  "noki" => array("ki", "si" => array("e", "e"), "pl" => array("kie", "ki")),
  "arki" => array("ki", "si" => array("je", "je"), "pl" => array("kie", "ji")),
  "kurki" => array("ki", "si" => array("je", "je"), "pl" => array("kie", "ji")),
  "järki" => array("ki", "si" => array("je", "je"), "pl" => array("kie", "ji")),
  "kärki" => array("ki", "si" => array("je", "je"), "pl" => array("kie", "ji")),
  "särki" => array("ki", "si" => array("je", "je"), "pl" => array("kie", "ji")),
  "kaski" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "vaski" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "leski" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "kiiski" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "viski" => array("i", "si" => array("i", "i"), "pl" => array("ie", "i")),
  "koski" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "poski" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "sääski" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "hetki" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "retki" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "putki" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "hauki" => array("ki", "si" => array("e", "e"), "pl" => array("kie", "i")),
  "tuki" => array("ki", "si" => array("e", "e"), "pl" => array("kie", "i")),
  "käki" => array("ki", "si" => array("e", "e"), "pl" => array("kie", "i")),
  "mäki" => array("ki", "si" => array("e", "e"), "pl" => array("kie", "i")),
  "väki" => array("ki", "si" => array("e", "e"), "pl" => array("kie", "i")),
  // -- li
  "banaali" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "kieli" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "mieli" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "pieli" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "tunneli" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "peli" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "veli" => array("i", "si" => array("je", "je"), "pl" => array("ie", "ji")),
  "peili" => array("", "si" => array("", ""), "pl" => array("lie", "lei")),
  "symboli" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "pistooli" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "huoli" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "nuoli" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "puoli" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "suoli" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "tuoli" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "sipuli" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "konsuli" => array("i", "si" => array("i", "i"), "pl" => array("eide", "ei")),
  "tuuli" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  // -- mi
  "niemi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "seimi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "nimi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "salmi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "helmi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "filmi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "tammi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "pommi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "nummi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "ei")),
  "suomi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "tuomi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "karmi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "sormi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "nurmi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "turismi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "kumi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "lumi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "kymi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "ei")),
  // -- ni
  "ääni" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "tulppaani" => array("i", "si" => array("i", "i"), "pl" => array("eide", "ei")),
  "kumppani" => array("i", "si" => array("i", "i"), "pl" => array("eide", "ei")),
  "pieni" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "sieni" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "insuliini" => array("i", "si" => array("i", "i"), "pl" => array("ie", "i")),
  "niini" => array("i", "si" => array("e", "e"), "pl" => array("ie", "ei")),
  "viini" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "sini" => array("i", "si" => array("e", "e"), "pl" => array("ie", "ei")),
  "onni" => array("i", "si" => array("e", "e"), "pl" => array("ie", "ei")),
  "ränni" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "telefoni" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "kortisoni" => array("i", "si" => array("i", "i"), "pl" => array("eide", "ei")),
  "betoni" => array("", "si" => array("", ""), "pl" => array("nie", "nei")),
  "juoni" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "suoni" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "tuoni" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "saarni" => array("i", "si" => array("e", "e"), "pl" => array("ie", "ei")),
  "torni" => array("i", "si" => array("i", "i"), "pl" => array("ie", "i")),
  "uni" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "tyyni" => array("i", "si" => array("e", "e"), "pl" => array("ie", "ei")),
  // -- pi
  "siipi" => array("pi", "si" => array("ve", "ve"), "pl" => array("pie", "vi")),
  "koipi" => array("pi", "si" => array("ve", "ve"), "pl" => array("pie", "vi")),
  "alpi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "ei")),
  "helpi" => array("pi", "si" => array("ve", "ve"), "pl" => array("pie", "vi")),
  "kilpi" => array("pi", "si" => array("ve", "ve"), "pl" => array("pie", "vi")),
  "lampi" => array("pi", "si" => array("me", "me"), "pl" => array("pie", "mi")),
  "sampi" => array("pi", "si" => array("me", "me"), "pl" => array("pie", "mi")),
  "lempi" => array("pi", "si" => array("me", "me"), "pl" => array("pie", "mi")),
  "suurempi" => array("pi", "si" => array("ma", "ma"), "pl" => array("pie", "mi")),
  "impi" => array("pi", "si" => array("me", "me"), "pl" => array("pie", "mi")),
  "kimpi" => array("pi", "si" => array("me", "me"), "pl" => array("pie", "mi")),
  "rimpi" => array("pi", "si" => array("me", "me"), "pl" => array("pie", "mi")),
  "umpi" => array("pi", "si" => array("me", "me"), "pl" => array("pimie", "mi")),
  "kumpi" => array("pi", "si" => array("ma", "ma"), "pl" => array("pie", "mi")),
  "appi" => array("pi", "si" => array("e", "e"), "pl" => array("pie", "ei")),
  "happi" => array("pi", "si" => array("e", "e"), "pl" => array("pie", "i")),
  "sinappi" => array("pi", "si" => array("i", "i"), "pl" => array("pie", "ei")),
  "sappi" => array("pi", "si" => array("e", "e"), "pl" => array("pie", "i")),
  "keppi" => array("pi", "si" => array("i", "i"), "pl" => array("pie", "ei")),
  "oppi" => array("pi", "si" => array("i", "i"), "pl" => array("pie", "ei")),
  "soppi" => array("pi", "si" => array("e", "e"), "pl" => array("pie", "ei")),
  "kuppi" => array("pi", "si" => array("i", "i"), "pl" => array("pie", "ei")),
  "tuppi" => array("pi", "si" => array("e", "e"), "pl" => array("pie", "ei")),
  "typpi" => array("pi", "si" => array("e", "e"), "pl" => array("pie", "ei")),
  "tyyppi" => array("pi", "si" => array("i", "i"), "pl" => array("pie", "ei")),
  "arpi" => array("pi", "si" => array("ve", "ve"), "pl" => array("pie", "vi")),
  "virpi" => array("pi", "si" => array("ve", "ve"), "pl" => array("pie", "pei")),
  "korpi" => array("pi", "si" => array("ve", "ve"), "pl" => array("pie", "vi")),
  "hupi" => array("pi", "si" => array("vi", "vi"), "pl" => array("pie", "vei")),
  "rupi" => array("pi", "si" => array("ve", "ve"), "pl" => array("pie", "vi")),
  "läpi" => array("pi", "si" => array("ve", "ve"), "pl" => array("pie", "vi")),
  // -- ri
  "aari" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "kaari" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "saari" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "sankari" => array("i", "si" => array("i", "i"), "pl" => array("eide", "ei")),
  "naamari" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "tuomari" => array("i", "si" => array("i", "i"), "pl" => array("eide", "ei")),
  "kamari" => array("ari", "si" => array("mari", "mari"), "pl" => array("arie", "marei")),
  "teeri" => array("i", "si" => array("e", "e"), "pl" => array("ie", "ei")),
  "bakteeri" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "terrieri" => array("i", "si" => array("i", "i"), "pl" => array("eide", "ei")),
  "vieri" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "summeri" => array("i", "si" => array("i", "i"), "pl" => array("eide", "i")),
  "paperi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "veri" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "toveri" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "hiiri" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "ori" => array("i", "si" => array("ii", "ii"), "pl" => array("iitte", "ii")),
  "kori" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "kuori" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "nuori" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "vuori" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "peluri" => array("i", "si" => array("i", "i"), "pl" => array("eide", "ei")),
  "kuuri" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "juuri" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "suuri" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "sääri" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  // -- si
  "paasi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  "lasi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "desi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "liesi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  "kesi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  "mesi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  "vesi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  "heisi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "reisi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "di")),
  "poliisi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "hiisi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "niisi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "sei")),
  "saksi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "viiksi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "vuoksi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "ei")),
  "uksi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "suksi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "sääksi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "jälsi" => array("si", "si" => array("le", "le"), "pl" => array("sie", "si")),
  "kansi" => array("si", "si" => array("ne", "ne"), "pl" => array("sie", "si")),
  "loosi" => array("", "si" => array("", ""), "pl" => array("sie", "ei")),
  "tosi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  "vuosi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  "hapsi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "lapsi" => array("si", "si" => array("se", "se"), "pl" => array("sie", "si")),
  "ripsi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "sei")),
  "hirsi" => array("si", "si" => array("re", "re"), "pl" => array("sie", "si")),
  "peitsi" => array("si", "si" => array("se", "se"), "pl" => array("sie", "si")),
  "veitsi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "ruotsi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "kvartsi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "kausi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  "jousi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "susi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  "uusi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  "kuusi" => array("si", "si" => array("se", "se"), "pl" => array("sie", "si")),
  "sysi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  "täysi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  "köysi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  "käsi" => array("si", "si" => array("de", "de"), "pl" => array("sie", "si")),
  // -- ti
  "vati" => array("ti", "si" => array("di", "di"), "pl" => array("tie", "dei")),
  "peti" => array("ti", "si" => array("di", "di"), "pl" => array("tie", "dei")),
  "haahti" => array("ti", "si" => array("de", "de"), "pl" => array("tie", "di")),
  "lahti" => array("ti", "si" => array("de", "de"), "pl" => array("tie", "di")),
  "vahti" => array("ti", "si" => array("di", "di"), "pl" => array("tie", "dei")),
  "lehti" => array("ti", "si" => array("de", "de"), "pl" => array("tie", "di")),
  "konvehti" => array("ti", "si" => array("di", "di"), "pl" => array("tie", "dei")),
  "pihti" => array("ti", "si" => array("di", "di"), "pl" => array("tie", "dei")),
  "vyyhti" => array("ti", "si" => array("de", "de"), "pl" => array("tie", "dei")),
  "tähti" => array("ti", "si" => array("de", "de"), "pl" => array("tie", "di")),
  "neiti" => array("ti", "si" => array("di", "di"), "pl" => array("tie", "dei")),
  "äiti" => array("ti", "si" => array("di", "di"), "pl" => array("tie", "dei")),
  "pelti" => array("ti", "si" => array("li", "li"), "pl" => array("tie", "lei")),
  "hollanti" => array("ti", "si" => array("ni", "ni"), "pl" => array("ie", "nei")),
  "tunti" => array("ti", "si" => array("ni", "ni"), "pl" => array("tie", "nei")),
  "koti" => array("ti", "si" => array("di", "di"), "pl" => array("tie", "dei")),
  "siisti" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "risti" => array("ti", "si" => array("ti", "ti"), "pl" => array("tie", "tei")),
  "salaatti" => array("ti", "si" => array("i", "i"), "pl" => array("tie", "ei")),
  "tatti" => array("ti", "si" => array("i", "i"), "pl" => array("tie", "ei")),
  "tauti" => array("ti", "si" => array("di", "di"), "pl" => array("tie", "dei")),
  // -- vi
  "savi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "substantiivi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "kivi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "palvi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "ei")),
  "talvi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "pilvi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "polvi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "pälvi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "ovi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "alkovi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "lovi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "povi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "muovi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "parvi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "sarvi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "hirvi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "torvi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "järvi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "kasvi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "huvi" => array("i", "si" => array("i", "i"), "pl" => array("ie", "ei")),
  "suvi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  "tyvi" => array("i", "si" => array("e", "e"), "pl" => array("ie", "i")),
  // -- ak
  "teak" => array("k", "si" => array("ki", "ki"), "pl" => array("kie", "kei")),
  // -- ck
  "rock" => array("k", "si" => array("ki", "ki"), "pl" => array("kie", "kei")),
  // -- nk
  "punk" => array("k", "si" => array("ki", "ki"), "pl" => array("kie", "kei")),
  // -- al
  "sammal" => array("l", "si" => array("lee", "lee"), "pl" => array("leide", "lei")),
  "taival" => array("val", "si" => array("palee", "palee"), "pl" => array("paleide", "palei")),
  // -- el
  "askel" => array("l", "si" => array("lee", "lee"), "pl" => array("lte", "lei")),
  "ommel" => array("mel", "si" => array("pelee", "pelee"), "pl" => array("peleide", "pelei")),
  "kannel" => array("nel", "si" => array("telee", "telee"), "pl" => array("teleide", "telei")),
  "opel" => array("l", "si" => array("li", "li"), "pl" => array("lie", "lei")),
  // -- am
  "edam" => array("m", "si" => array("mi", "mi"), "pl" => array("mie", "mei")),
  // -- um
  "kalsium" => array("m", "si" => array("mi", "mi"), "pl" => array("mie", "mei")),
  // -- an
  "fan" => array("n", "si" => array("ni", "ni"), "pl" => array("nie", "nei")),
  "hapan" => array("an", "si" => array("pame", "pame"), "pl" => array("pamie", "pami")),
  "muuan" => array("an", "si" => array("tama", "tama"), "pl" => array("tamie", "tami")),
  // -- en
  "siemen" => array("n", "si" => array("ne", "ne"), "pl" => array("nie", "ni")),
  "nainen" => array("nen", "si" => array("se", "se"), "pl" => array("sie", "si")),
  "punainen" => array("inen", "si" => array("ise", "ise"), "pl" => array("ste", "isei")),
  "topografinen" => array("nen", "si" => array("se", "se"), "pl" => array("sie", "si")),
  "filosofinen" => array("nen", "si" => array("se", "se"), "pl" => array("sie", "si")),
  "psykologinen" => array("nen", "si" => array("se", "se"), "pl" => array("sie", "si")),
  "psyykkinen" => array("nen", "si" => array("se", "se"), "pl" => array("ste", "si")),
  "ironinen" => array("nen", "si" => array("se", "se"), "pl" => array("sie", "si")),
  "eeppinen" => array("pinen", "si" => array("pise", "pise"), "pl" => array("piste", "pisi")),
  "allegorinen" => array("nen", "si" => array("se", "se"), "pl" => array("sie", "si")),
  "kriittinen" => array("nen", "si" => array("se", "se"), "pl" => array("ste", "si")),
  "relatiivinen" => array("nen", "si" => array("se", "se"), "pl" => array("ste", "si")),
  "hevonen" => array("nen", "si" => array("se", "se"), "pl" => array("sie", "si")),
  "vasen" => array("n", "si" => array("mma", "mma"), "pl" => array("mpie", "mmi")),
  "ahven" => array("n", "si" => array("ne", "ne"), "pl" => array("nie", "ni")),
  "säen" => array("en", "si" => array("kene", "kene"), "pl" => array("keneide", "kenei")),
  "puoleen" => array("en", "si" => array("ise", "ise"), "pl" => array("iste", "ise")),
  "rauhanen" => array("nen", "si" => array("se", "se"), "pl" => array("ste", "si")),
  "ien" => array("en", "si" => array("kene", "kene"), "pl" => array("kenie", "keni")),
  // -- in
  "kasvain" => array("in", "si" => array("ime", "ime"), "pl" => array("imie", "imi")),
  "kaadin" => array("din", "si" => array("time", "time"), "pl" => array("timie", "timi")),
  "pahin" => array("in", "si" => array("imma", "imma"), "pl" => array("impie", "immi")),
  "poljin" => array("jin", "si" => array("kime", "kime"), "pl" => array("kimie", "kimi")),
  "elin" => array("n", "si" => array("me", "me"), "pl" => array("mie", "mi")),
  "sivellin" => array("lin", "si" => array("time", "time"), "pl" => array("timie", "timi")),
  "lämmin" => array("min", "si" => array("pimä", "pimä"), "pl" => array("pimie", "pimi")),
  "vaimennin" => array("nin", "si" => array("time", "time"), "pl" => array("timie", "timi")),
  "kerroin" => array("roin", "si" => array("toime", "toime"), "pl" => array("toimie", "toimi")),
  "kiharrin" => array("rin", "si" => array("time", "time"), "pl" => array("timie", "timi")),
  "sisin" => array("in", "si" => array("ime", "ime"), "pl" => array("imie", "imi")),
  "suodatin" => array("in", "si" => array("time", "time"), "pl" => array("timie", "timi")),
  "kuljetin" => array("in", "si" => array("time", "time"), "pl" => array("timie", "timi")),
  "teroitin" => array("in", "si" => array("time", "time"), "pl" => array("timie", "timi")),
  "uistin" => array("n", "si" => array("me", "me"), "pl" => array("mie", "mi")),
  "sumutin" => array("in", "si" => array("time", "time"), "pl" => array("timie", "timi")),
  "puin" => array("in", "si" => array("kime", "kime"), "pl" => array("kimie", "kimi")),
  "istuin" => array("n", "si" => array("me", "me"), "pl" => array("mie", "mi")),
  "kaavin" => array("vin", "si" => array("pime", "pime"), "pl" => array("pimie", "pimi")),
  // -- on
  "stadion" => array("n", "si" => array("ni", "ni"), "pl" => array("ide", "nei")),
  "onneton" => array("on", "si" => array("toma", "toma"), "pl" => array("tomie", "tomi")),
  "alaston" => array("n", "si" => array("ma", "ma"), "pl" => array("mie", "mi")),
  // -- un
  "laidun" => array("dun", "si" => array("tume", "tume"), "pl" => array("tumie", "tumi")),
  // -- än
  "sydän" => array("n", "si" => array("mme", "mme"), "pl" => array("mmie", "mmi")),
  "hän" => array("än", "si" => array("äne", "äne"), "pl" => array("eidä", "ei")),
  // -- eo
  "video" => array("o", "si" => array("o", "o"), "pl" => array("oide", "oi")),
  // -- io
  "illuusio" => array("o", "si" => array("o", "o"), "pl" => array("oide", "oi")),
  "obligaatio" => array("o", "si" => array("o", "o"), "pl" => array("oide", "oi")),
  "traditio" => array("o", "si" => array("o", "o"), "pl" => array("oide", "oi")),
  "funktio" => array("o", "si" => array("o", "o"), "pl" => array("oide", "oi")),
  "autio" => array("o", "si" => array("o", "o"), "pl" => array("oide", "oi")),
  "resoluutio" => array("o", "si" => array("o", "o"), "pl" => array("oide", "oi")),
  // -- ko
  "rako" => array("ko", "si" => array("o", "o"), "pl" => array("koje", "oi")),
  "teko" => array("ko", "si" => array("o", "o"), "pl" => array("koje", "oi")),
  "vihko" => array("ko", "si" => array("o", "o"), "pl" => array("koje", "oi")),
  "laatikko" => array("ko", "si" => array("o", "o"), "pl" => array("oide", "oi")),
  "verkko" => array("ko", "si" => array("o", "o"), "pl" => array("koje", "oi")),
  "halko" => array("ko", "si" => array("o", "o"), "pl" => array("koje", "oi")),
  "hanko" => array("ko", "si" => array("go", "go"), "pl" => array("koje", "goi")),
  "alanko" => array("ko", "si" => array("go", "go"), "pl" => array("koje", "goi")),
  "koko" => array("ko", "si" => array("o", "o"), "pl" => array("koje", "oi")),
  "ruoko" => array("ko", "si" => array("'o", "'o"), "pl" => array("koje", "'oi")),
  "usko" => array("o", "si" => array("o", "o"), "pl" => array("oje", "oi")),
  // -- lo
  "valo" => array("o", "si" => array("o", "o"), "pl" => array("oje", "oi")),
  "hontelo" => array("lo", "si" => array("lo", "lo"), "pl" => array("loide", "loi")),
  // -- no
  "pano" => array("no", "si" => array("no", "no"), "pl" => array("noje", "noi")),
  // -- oo
  "trikoo" => array("o", "si" => array("", ""), "pl" => array("ide", "oi")),
  "tienoo" => array("o", "si" => array("o", "o"), "pl" => array("ide", "oi")),
  // -- po
  "lepo" => array("po", "si" => array("vo", "vo"), "pl" => array("poje", "voi")),
  "sampo" => array("po", "si" => array("mo", "mo"), "pl" => array("poje", "moi")),
  "mopo" => array("po", "si" => array("po", "po"), "pl" => array("poje", "poi")),
  "kippo" => array("po", "si" => array("o", "o"), "pl" => array("poje", "oi")),
  // -- ro
  "numero" => array("o", "si" => array("o", "o"), "pl" => array("oide", "oi")),
  // -- to
  "pato" => array("to", "si" => array("do", "do"), "pl" => array("toje", "doi")),
  "tieto" => array("to", "si" => array("do", "do"), "pl" => array("toje", "doi")),
  "johto" => array("to", "si" => array("do", "do"), "pl" => array("toje", "doi")),
  "taito" => array("to", "si" => array("do", "do"), "pl" => array("toje", "doi")),
  "aalto" => array("to", "si" => array("lo", "lo"), "pl" => array("toje", "loi")),
  "anto" => array("to", "si" => array("no", "no"), "pl" => array("toje", "noi")),
  "avanto" => array("to", "si" => array("no", "no"), "pl" => array("toje", "noi")),
  "muoto" => array("to", "si" => array("do", "do"), "pl" => array("toje", "doi")),
  "kaarto" => array("to", "si" => array("ro", "ro"), "pl" => array("toje", "roi")),
  "koneisto" => array("o", "si" => array("o", "o"), "pl" => array("oide", "oi")),
  "aarteisto" => array("isto", "si" => array("histo", "histo"), "pl" => array("istoide", "istoi")),
  "pihatto" => array("to", "si" => array("o", "o"), "pl" => array("toje", "oi")),
  "liitto" => array("to", "si" => array("o", "o"), "pl" => array("toje", "oi")),
  "auto" => array("o", "si" => array("o", "o"), "pl" => array("oje", "oi")),
  "leuto" => array("to", "si" => array("do", "do"), "pl" => array("toje", "doi")),
  // -- uo
  "suo" => array("uo", "si" => array("uo", "uo"), "pl" => array("oide", "oi")),
  // -- op
  "pop" => array("p", "si" => array("pi", "pi"), "pl" => array("pie", "pei")),
  // -- ar
  "maar" => array("r", "si" => array("ri", "ri"), "pl" => array("rie", "rei")),
  "udar" => array("dar", "si" => array("taree", "taree"), "pl" => array("tareide", "tarei")),
  "piennar" => array("nar", "si" => array("taree", "taree"), "pl" => array("tareide", "tarei")),
  "sisar" => array("r", "si" => array("re", "re"), "pl" => array("rie", "ri")),
  // -- er
  "penger" => array("ger", "si" => array("keree", "keree"), "pl" => array("kereide", "kerei")),
  "kinner" => array("ner", "si" => array("teree", "teree"), "pl" => array("tereide", "terei")),
  "auer" => array("er", "si" => array("teree", "teree"), "pl" => array("tereitte", "terei")),
  // -- är
  "tytär" => array("är", "si" => array("täre", "täre"), "pl" => array("tärie", "täri")),
  // -- as
  "ahdas" => array("das", "si" => array("taa", "taa"), "pl" => array("taide", "tai")),
  "kangas" => array("gas", "si" => array("kaa", "kaa"), "pl" => array("kaide", "kai")),
  "lihas" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "antelias" => array("s", "si" => array("a", "a"), "pl" => array("ide", "i")),
  "utelias" => array("s", "si" => array("a", "a"), "pl" => array("ide", "i")),
  "laupias" => array("ias", "si" => array("iaa", "iaa"), "pl" => array("iaide", "iai")),
  "rakas" => array("as", "si" => array("kaa", "kaa"), "pl" => array("kaide", "kai")),
  "maineikas" => array("as", "si" => array("kaa", "kaa"), "pl" => array("kaide", "kai")),
  "raskas" => array("s", "si" => array("a", "a"), "pl" => array("ide", "i")),
  "valas" => array("s", "si" => array("a", "a"), "pl" => array("ide", "i")),
  "sotilas" => array("s", "si" => array("a", "a"), "pl" => array("ide", "i")),
  "allas" => array("las", "si" => array("taa", "taa"), "pl" => array("taide", "tai")),
  "hammas" => array("mas", "si" => array("paa", "paa"), "pl" => array("paide", "pai")),
  "ananas" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "kinnas" => array("nas", "si" => array("taa", "taa"), "pl" => array("taide", "tai")),
  "saapas" => array("as", "si" => array("paa", "paa"), "pl" => array("paide", "pai")),
  "paras" => array("as", "si" => array("haa", "haa"), "pl" => array("haide", "hai")),
  "varas" => array("as", "si" => array("kaa", "kaa"), "pl" => array("kaide", "kai")),
  "vieras" => array("s", "si" => array("a", "a"), "pl" => array("ide", "i")),
  "koiras" => array("s", "si" => array("a", "a"), "pl" => array("ide", "i")),
  "harras" => array("ras", "si" => array("taa", "taa"), "pl" => array("taide", "tai")),
  "kahdeksas" => array("s", "si" => array("nne", "nne"), "pl" => array("nsie", "nsi")),
  "porsas" => array("s", "si" => array("a", "a"), "pl" => array("ide", "i")),
  "ratas" => array("as", "si" => array("taa", "taa"), "pl" => array("taide", "tai")),
  "kiuas" => array("as", "si" => array("kaa", "kaa"), "pl" => array("kaide", "kai")),
  "autuas" => array("as", "si" => array("aa", "aa"), "pl" => array("aide", "ai")),
  "varvas" => array("vas", "si" => array("paa", "paa"), "pl" => array("paide", "pai")),
  // -- es
  "ies" => array("es", "si" => array("kee", "kee"), "pl" => array("keide", "kei")),
  "mies" => array("s", "si" => array("he", "he"), "pl" => array("hie", "hi")),
  "bisnes" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "kirves" => array("s", "si" => array("e", "e"), "pl" => array("ide", "i")),
  // -- is
  "julkkis" => array("is", "si" => array("ikse", "ikse"), "pl" => array("iksie", "iksi")),
  "valmis" => array("is", "si" => array("ii", "ii"), "pl" => array("iide", "ii")),
  "kaunis" => array("is", "si" => array("ii", "ii"), "pl" => array("iide", "ii")),
  "kauris" => array("is", "si" => array("ii", "ii"), "pl" => array("iide", "ii")),
  "raitis" => array("is", "si" => array("tii", "tii"), "pl" => array("tiide", "tii")),
  "altis" => array("is", "si" => array("tii", "tii"), "pl" => array("tiide", "tii")),
  "ruis" => array("is", "si" => array("kii", "kii"), "pl" => array("kiide", "kii")),
  // -- os
  "uros" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  // -- us
  "vapaus" => array("s", "si" => array("de", "de"), "pl" => array("ksie", "ksi")),
  "ohjaus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "pakkaus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "rakkaus" => array("s", "si" => array("de", "de"), "pl" => array("ksie", "ksi")),
  "leikkaus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "purkaus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "raskaus" => array("s", "si" => array("de", "de"), "pl" => array("ksie", "ksi")),
  "taklaus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "kaipaus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "toppaus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "lupaus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "runsaus" => array("s", "si" => array("de", "de"), "pl" => array("ksie", "ksi")),
  "katsaus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "kiusaus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "vastaus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "pilkahdus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "kalleus" => array("s", "si" => array("de", "de"), "pl" => array("ksie", "ksi")),
  "ohjus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "keskus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "kaulus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "kertomus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "rakennus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "tarjous" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "heikkous" => array("s", "si" => array("de", "de"), "pl" => array("ksie", "ksi")),
  "kokous" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "talous" => array("s", "si" => array("de", "de"), "pl" => array("ksie", "ksi")),
  "vierus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "aivoitus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "jaotus" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  // -- ys
  "yhteys" => array("s", "si" => array("de", "de"), "pl" => array("ksie", "ksi")),
  "pysähdys" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "kyljys" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "päälys" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "väsymys" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "kypsennys" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "lämmitys" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "määräys" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  // -- äs
  "iäkäs" => array("äs", "si" => array("kää", "kää"), "pl" => array("käide", "käi")),
  "teräs" => array("s", "si" => array("kse", "kse"), "pl" => array("ksie", "ksi")),
  "pylväs" => array("s", "si" => array("ä", "ä"), "pl" => array("ide", "i")),
  // -- et
  "alkeet" => array("et", "si" => array("ide", "ide"), "pl" => array("ide", "i")),
  "harteet" => array("et", "si" => array("itte", "itte"), "pl" => array("itte", "i")),
  "länget" => array("get", "si" => array("ge", "ge"), "pl" => array("kie", "gi")),
  "suitset" => array("et", "si" => array("ie", "ie"), "pl" => array("ie", "i")),
  "päitset" => array("et", "si" => array("e", "e"), "pl" => array("ie", "i")),
  // -- it
  "parfait" => array("", "si" => array("'", "'"), "pl" => array("e", "")),
  "pihdit" => array("dit", "si" => array("tie", "tie"), "pl" => array("tie", "dei")),
  "tanssit" => array("it", "si" => array("ie", "ie"), "pl" => array("ie", "ie")),
  // -- ot
  "aivot" => array("ot", "si" => array("oje", "oje"), "pl" => array("oje", "oi")),
  // -- ut
  "kuollut" => array("lut", "si" => array("lee", "lee"), "pl" => array("leide", "lei")),
  "punonut" => array("nut", "si" => array("nee", "nee"), "pl" => array("neide", "nei")),
  "airut" => array("t", "si" => array("e", "e"), "pl" => array("eide", "ei")),
  "purrut" => array("rut", "si" => array("ree", "ree"), "pl" => array("reide", "rei")),
  "juossut" => array("sut", "si" => array("see", "see"), "pl" => array("seide", "sei")),
  // -- yt
  "pöksyt" => array("yt", "si" => array("yje", "yje"), "pl" => array("yje", "yi")),
  "neitsyt" => array("yt", "si" => array("ye", "ye"), "pl" => array("yeide", "yi")),
  // -- ät
  "kevät" => array("t", "si" => array("ä", "ä"), "pl" => array("ide", "i")),
  // -- iu
  "tiu" => array("u", "si" => array("u", "u"), "pl" => array("u'uje" ,"u'ui")),
  // -- ku
  "haku" => array("ku", "si" => array("u", "u"), "pl" => array("kuje", "ui")),
  "laku" => array("u", "si" => array("u", "u"), "pl" => array("uje", "ui")),
  "maku" => array("ku", "si" => array("u", "u"), "pl" => array("kuje", "ui")),
  "suihku" => array("u", "si" => array("u", "u"), "pl" => array("uje", "ui")),
  "kinkku" => array("ku", "si" => array("u", "u"), "pl" => array("kuje", "ui")),
  "alku" => array("ku", "si" => array("u", "u"), "pl" => array("kuje", "ui")),
  "hinku" => array("ku", "si" => array("gu", "gu"), "pl" => array("kuje", "gui")),
  "ruisku" => array("u", "si" => array("u", "u"), "pl" => array("uje", "ui")),
  "luku" => array("ku", "si" => array("vu", "vu"), "pl" => array("kuje", "vui")),
  "tiuku" => array("ku", "si" => array("'u", "'u"), "pl" => array("kuje", "u'ui")),
  // -- lu
  "arvelu" => array("u", "si" => array("u", "u"), "pl" => array("uide", "ui")),
  "taulu" => array("u", "si" => array("u", "u"), "pl" => array("uje", "ui")),
  // -- nu
  "gnu" => array("u", "si" => array("u", "u"), "pl" => array("uide", "ui")),
  // -- pu
  "apu" => array("pu", "si" => array("vu", "vu"), "pl" => array("puje", "vui")),
  "kumpu" => array("pu", "si" => array("mu", "mu"), "pl" => array("puje", "mui")),
  "hoppu" => array("pu", "si" => array("u", "u"), "pl" => array("puje", "ui")),
  // -- ru
  "kiiru" => array("u", "si" => array("uu", "uu"), "pl" => array("eide", "ei")),
  "piru" => array("ru", "si" => array("ru", "ru"), "pl" => array("ruje", "rui")),
  "koru" => array("u", "si" => array("u", "u"), "pl" => array("uje", "ui")),
  // -- tu
  "laatu" => array("tu", "si" => array("du", "du"), "pl" => array("tuje", "dui")),
  "kohtu" => array("tu", "si" => array("du", "du"), "pl" => array("tuje", "dui")),
  "kuitu" => array("tu", "si" => array("du", "du"), "pl" => array("tuje", "dui")),
  "katseltu" => array("tu", "si" => array("lu", "lu"), "pl" => array("tuje", "lui")),
  "oltu" => array("tu", "si" => array("lu", "lu"), "pl" => array("tuje", "lui")),
  "lintu" => array("tu", "si" => array("nu", "nu"), "pl" => array("tuje", "nui")),
  "rotu" => array("tu", "si" => array("du", "du"), "pl" => array("tuje", "rui")),
  "purtu" => array("tu", "si" => array("ru", "ru"), "pl" => array("tuje", "tui")),
  "nuolaistu" => array("tu", "si" => array("tu", "tu"), "pl" => array("tuje", "tui")),
  "hattu" => array("tu", "si" => array("u", "u"), "pl" => array("tuje", "ui")),
  "raamattu" => array("tu", "si" => array("u", "u"), "pl" => array("tuje", "ui")),
  "puhuttu" => array("tu", "si" => array("u", "u"), "pl" => array("tuje", "ui")),
  "seutu" => array("tu", "si" => array("du", "du"), "pl" => array("tuje", "dui")),
  // -- uu
  "leikkuu" => array("u", "si" => array("u", "u"), "pl" => array("uksie", "uksi")),
  "puu" => array("u", "si" => array("u", "u"), "pl" => array("ide", "i")),
  // -- ay
  "spray" => array("y", "si" => array("y", "y"), "pl" => array("yide", "y")),
  // -- ky
  "myrkky" => array("ky", "si" => array("y", "y"), "pl" => array("kyje", "kyi")),
  "hylky" => array("ky", "si" => array("y", "y"), "pl" => array("kyje", "kei")),
  "sänky" => array("ky", "si" => array("gy", "gy"), "pl" => array("kyje", "gyi")),
  "myrsky" => array("y", "si" => array("y", "y"), "pl" => array("yje", "yi")),
  "kyky" => array("ky", "si" => array("vy", "vy"), "pl" => array("kyje", "vyi")),
  // -- py
  "kylpy" => array("py", "si" => array("vy", "vy"), "pl" => array("pyje", "vyi")),
  "hyppy" => array("py", "si" => array("y", "y"), "pl" => array("pyje", "yi")),
  // -- ty
  "lyhty" => array("ty", "si" => array("dy", "dy"), "pl" => array("tyje", "dyi")),
  "synty" => array("ty", "si" => array("ny", "ny"), "pl" => array("tyje", "nyi")),
  "yhdistetty" => array("ty", "si" => array("y", "y"), "pl" => array("tyje", "yi")),
  // -- yy
  "revyy" => array("y", "si" => array("y", "y"), "pl" => array("ide", "i")),
  // -- ä
  "myyjä" => array("jä", "si" => array("jä", "jä"), "pl" => array("jie", "ji")),
  "ikä" => array("kä", "si" => array("ä", "ä"), "pl" => array("kie", "ki")),
  "reikä" => array("kä", "si" => array("ä", "ä"), "pl" => array("kie", "'i")),
  "selkä" => array("kä", "si" => array("ä", "ä"), "pl" => array("kie", "i")),
  "ylkä" => array("kä", "si" => array("jä", "jä"), "pl" => array("kie", "i")),
  "härkä" => array("kä", "si" => array("ä", "ä"), "pl" => array("kie", "i")),
  "pitkä" => array("ä", "si" => array("ä", "ä"), "pl" => array("ie", "i")),
  "keväämmällä" => array("lä", "si" => array("lä", "lä"), "pl" => array("leide", "lei")),
  "minä" => array("inä", "si" => array("inu", "inu"), "pl" => array("eidä", "ei")),
  "sinä" => array("sinä", "si" => array("sinun", "sinun"), "pl" => array("teidä", "tei")),
  "leipä" => array("pä", "si" => array("vä", "vä"), "pl" => array("pie", "vi")),
  "emäntä" => array("tä", "si" => array("nä", "nä"), "pl" => array("tie", "ni")),
  "kenttä" => array("tä", "si" => array("ä", "ä"), "pl" => array("tie", "ti")),
  "pöytä" => array("tä", "si" => array("dä", "dä"), "pl" => array("tie", "di")),
  // -- ö
  "sähkö" => array("ö", "si" => array("ö", "ö"), "pl" => array("öje", "öi")),
  "kätkö" => array("ö", "si" => array("ö", "ö"), "pl" => array("öje", "öi")),
  "kiinteistö" => array("tö", "si" => array("tö", "tö"), "pl" => array("töje", "töi")),
  "enemmistö" => array("ö", "si" => array("ö", "ö"), "pl" => array("öide", "öi")),
  "löytö" => array("tö", "si" => array("dö", "dö"), "pl" => array("töje", "döi")),
  "yö" => array("yö", "si" => array("yö", "yö"), "pl" => array("öide", "öi")),

);
